version: "3.8"

services:
  mysql_db:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_ROOT_HOST="%"
      - MYSQL_ROOT_PASSWORD="langrinda00912"
      - MYSQL_DATABASE="commit_creator"
      - MYSQL_USER="netflams10"
      - MYSQL_PASSWORD="langrinda00912"
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql_data/:/var/lib/mysql
    networks: 
      - database

  postgres:
    container_name: db
    image: postgres
    volumes: 
      - ./postgres_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB="commit_creator"
      - POSTGRES_USER="netflams10"
      - POSTGRES_PASSWORD=langrinda00912
    ports:
      - "5432:5432"
    networks:
      - database

  mongo_db: 
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db:rw
    restart: always
    networks:
      - database

volumes:
  mysql_data:
  postgres_data:
  mongo_data:
networks:
  database:
    driver: bridge
