apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip-service
  namespace: database
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    persistent_database: mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32000