apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip-service
  namespace: database
spec:
  type: ClusterIP
  selector:
    persistent_database: mysql
  ports:
    - port: 3306
      targetPort: 3306