apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  namespace: database
spec:
  type: ClusterIP
  selector:
    persistent_database: postgress
  ports:
    - port: 5432
      targetPort: 5432
