apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      persistent_database: postgress
  template:
    metadata:
      labels:
        persistent_database: postgress
    spec:
      volumes:
      - name: postgres-storage      
        persistentVolumeClaim:
          claimName: database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        env:
        - name: POSTGRES_DB
          value: auth_db
        - name: POSTGRES_USER
          value: netflams10
        - name: POSTGRES_PASSWORD
          value: my_mind_is_blanc_and black